(use-modules (asm asm)
	     (asm x86)
	     (compiler base))

(test-begin "asm")

;; (test-equal "addq $1, $2" (string-trim (instr->string (addq ($int 1) ($int 2)))))
;; (test-equal "addq $1, %rsp" (string-trim (instr->string (addq ($int 1) rsp))))

;; (test-equal "negq 1" (asm->string (negq 1)))
;; (test-equal "retq" (asm->string (retq)))

(let ((p (progn "prog1.rm")))
  (let ((b ($x86 "main")))
    (add-code b ($addq ($int 10) rax))
    (add-code b ($addq ($int 32) rax))
    (add-code b ($retq))
    (add-block p b))
  (let ((c ($x86 "test")))
    (add-code c ($addq ($int 10) rax))
    (add-code c ($addq ($int 32) rax))
    (add-code c ($retq))
    (add-block p c))
  (format #t "~a" p))
  ;; (append-asm a (addq ($int 1) ($int 2)))
  ;; (let ((main (block ($label "main")))
  ;; 	(p (block ($label "print"))))
  ;;   (append-asm main (movq ($int 10) rax))
  ;;   (append-asm main (addq ($int 32) rax))
  ;;   (append-asm main (retq))
  ;;   (append-asm a main))
  ;; (format #t "~a" a))

(test-end "asm")
